.rm80







                                                    2¹ December¬ 1987



Dalå Burkett¬ Administrator
Operationó Section
Divisioî oæ Fisheries
Illinoió Dept® oæ Conservation
60° Nortè Granä Avenue West
Springfield¬ IÌ 62706


Deaò Dale:

Thió letteò summarizeó thå changeó thaô havå takeî placå iî ouò planó foò thå 
Federaì Aiä Projecô "Sporô Fisè Uså oæ Musseì Beds¢ witè particulaò attentioî 
devoteä tï changeó iî proposeä budgets.

Thå originaì plaî outlineä iî thå prå-proposaì (Exhibiô A© waó foò á ³-yeaò 
studù consistinç oæ (1© á laboratorù studù tï determinå whetheò fisè prefeò 
musseì shelló tï otheò substratå typeó anä (2© á fielä studù tï validatå resultó 
oæ thå laboratorù study®  Thå emphasió waó oî thå laboratorù studù anä efforô 
planneä foò thå fielä studù waó minimal®  

Initiallù wå haä stafæ availablå aô thå Riveò Researcè Laboratorù (RRL© tï helğ 
ouô oî thió projecô (i.e.¬ McLuckie¬ Douglas¬ Blodgett)®  McLuckiå anä Douglaó 
werå partiallù fundeä bù otheò projectó anä availablå tï worë parô oæ thå yeaò 
oî thå Sporô Fish/Musseì Beä project®  Blodgetô waó tï bå paiä witè Generaì 
Revenuå Fundó ("harä money"© anä woulä havå requireä nï federaì fundinç froí thå 
project®  Wå alsï planneä tï uså á graduatå studenô workinç witè Dr® Richarä 
Andersoî (Westerî Illinoió University¬ Macomb¬ IL© tï providå assistancå foò thå 
duratioî oæ thå project®  Responsibilitieó foò desigî anä administratioî foò thå 
projecô werå tï bå shareä bù Sparks¬ Andersoî anä Blodgetô ­­ agaiî aô nï cosô 
tï thå project.

Thå totaì estimateä projecô cosô foò thå prå-proposaì waó $84,31· and¬ aó 
indicateä oî thå prå-proposaì form¬ thaô diä noô includå 20¥ indirecô costs®  Á 
photocopù oæ thå itemizeä budgeô useä tï calculatå estimateä costó foò thå prå-
proposaì ió encloseä (Exhibiô B).

Whilå thå prå-proposaì waó beinç typeä aô thå RRÌ anä senô tï thå DOC¬ Sparkó 
waó aô ouò maiî officå oî thå Universitù oæ Illinoió campus¬ Champaign/Urbana¬ 
IL®  Hå becamå concerneä abouô thå availabilitù oæ thå personneì wå haä planneä 
oî usinç (Blodgett¬ McLuckie¬ Douglas¬ anä á graduatå student)®  Iô appeareä Šthaô fundinç foò McLuckiå anä Douglaó woulä lapså beforå thå Musseì Bed/Sporô 
Fisè projecô starteä anä theù woulä bå seekinç employmenô elsewhere¬ anä nï 
"harä money¢ waó availablå foò Blodgett®  Therefore¬ Sparkó recalculateä thå 
budgeô baseä oî thå assumptioî thaô thå projecô woulä neeä tï providå fundó foò 
alì personneì excepô Sparks®  Oî 1´ Novembeò 1986¬ á letteò tï Burketô froí 
Sparkó (Exhibiô C© indicateä costó oî thå prå-proposaì haä beeî underestimated®  
Thå ne÷ estimateä cosô waó $165,11² (excludinç 20¥ indirecô costs)®  

Afteò consultationó witè thå DOÃ anä prioò tï submittinç thå Applicatioî foò 
Federaì Assistancå (AFA© tï thå DOÃ iî Februarù 1987¬ modificationó werå madå tï 
thå experimentaì desigî ®  Thå fielä studù waó eliminateä froí INHÓ project¬ buô 
thå onlù significanô cosô reductioî waó iî travel®  Á morå intensivå laboratorù 
efforô oveò á ²-yeaò projecô waó planneä insteaä oæ thå previouslù requesteä ³-
yeaò project®  Wå anticipateä iô woulä bå easieò tï hirå fulì-timå employeeó foò 
² yearó insteaä oæ parô-timå employeeó foò ³ years®  Á posô-doã oò MÓ-leveì 
salarù waó includeä tï providå á fulì-timå projecô manageò durinç thå twï yeaò 
project®  Iî addition¬ fundó werå addeä tï offseô increaseä utilitù expenseó 
resultinç froí uså oæ laboratorù spacå aô thå DOÃ Fisherieó Fielä Headquarteró 
iî Havana¬ IL®  Photocopieó oæ theså budgets¬ whicè werå submitteä witè thå AFA¬ 
arå attacheä (Exhibitó Ä anä E).

Iî summary¬ thå cosô oæ thå studù increaseä significantlù froí thå prå-proposaì 
becauså personneì uncertaintieó requireä thaô thå proposeä budgeô includå 
additionaì fundó foò á fulì-timå senioò leveì projecô manageò anä á fulì-timå 
technician®  Wheî thå fielä studù waó dropped¬ thå studù duratioî waó reduceä 
froí ³ yearó tï ² yearó anä thå budgeô droppeä froí $165,11² ($198,13´ witè 
indirecô costs© tï $128,22° (153,93¶ witè indirecô costs)®  Á summarù tablå 
(Exhibiô F© outlineó thå estimateä costó foò thå (1© prå-proposaì budget¬ (2© 
reviseä prå-proposaì budget¬ anä (3)thå AFÁ budget.

Shoulä yoõ neeä furtheò informatioî oò clarification¬ contacô me.





                                                    Sincerelù yours,



                                                    K® Douglaó Blodgett
                                                    Associatå Researcè Biologist


Attachmentó (6)

ccº Sparks¬ Gorden¬ Hale 
