                          JOB AVAILABLE

                         FISÈ BEHAVIORIST


NATURAÌ HISTORÙ SURVEY¬ RIVEÒ RESEARCÈ LABORATORY¬ HAVANA¬ ILLINOIÓ ­­ 
FISÈ BEHAVIORIST(MÓ OÒ PHÄ LEVEL© ­­ ONÅ POSITIOÎ ­­ Twï-yeaò temporarù 
position®  Salarù $20,004 tï $23,004 peò year¬ pluó benefits¬ dependinç 
oî experience®  Wilì evaluatå whetheò ´ specieó oæ sporô fisè anä ± foragå 
specieó prefeò substrateó containinç livå musseló tï substrateó witè 
shelló onlù anä substrateó witè nï shells®  Effectó oæ photoperioä anä 
temperaturå oî fisè selectioî oæ substratå alsï wilì bå evaluated®  Thå 
biologisô musô bå ablå toº (1© maintaiî fisè anä musseló iî thå laboratory¬ 
(2© construcô flo÷-througè tesô chambers¬ (3© collaboratå witè aî 
electricaì engineeò whï ió interfacinç á videï camerá anä á computeò anä 
developinç programó foò datá collection¬ analysió anä display¬ (4© 
collaboratå witè biologistó conductinç á separatå fielä projecô tï verifù 
laboratorù results¬ (5© superviså á technicaì assistant¬ anä (5© analyzå 
thå datá anä writå thå summarù reports®  Preferencå wilì bå giveî tï 
biologistó witè relevanô experiencå anä demonstrateä analyticaì anä 
writinç ability¬ whicè shoulä bå describeä iî á letteò oæ applicatioî anä 
iî á resume® Includå thå addresseó anä phonå numberó oæ ³ referenceó anä 
senä prioò tï 1µ Decembeò 198· toº Dr® Richarä E® Sparks¬ Riveò Researcè 
Laboratory¬ Boø 599¬ Havana¬ IÌ 62644¬ (309© 54³-3105/3950®  Thå Illinoió 
Naturaì Historù Surveù ió aî affirmativå action¯ equaì opportunitù 
employer.