.uj off
.ps off
.cw 12
.ul off
.pc45
.mt3
.mb6
.pn1

Narrative:  Value of Mussel Beds to Sport Fisheries


1.  Needs
 
     One goaì oæ thå Strategiã Plaî foò Riveró anä Streamó iî 

Illinoió ió tï increaså thå quantitù anä qualitù oæ sporô fishinç 

opportunitieó througè propeò fisherieó managemenô (Illinoió 

Departmenô oæ Conservatioî 1986)®  Á majoò obstaclå tï achievinç 

thió goaì ió habitaô degradatioî whicè continueó tï reducå 

fisherieó resourceó iî thå streamó anä riveró oæ Illinois®  Propeò 

managemenô oæ thå sporô fisherù requireó identification¬ 

preservation¬ anä enhancemenô oæ thoså habitató mosô attractivå tï 

sporô fisè foò spawning¬ feeding¬ anä foò nurserù areas®  Althougè 

iô ió suspecteä thaô musseì bedó arå selecteä oveò predominanô 

substrateó bù sporô fish¬ thå relativå significancå oæ thå bedó tï 

thå sporô fisherù haó noô beeî evaluated®  Iæ sporô fisheó selecô 

musseì bedó oveò predominant substrates¬ increaseä efforô tï 

preservå anä enhancå musseì bedó shoulä contributå tï thå 

protectioî anä enhancemenô oæ sporô fisheries.


2.  Projecô Objective

     Tï evaluatå thå significancå oæ musseì bedó tï sporô 

fisherieó, usinç á laboratorù approacè.


3.  Expecteä Resultó anä Benefits

     Thió researcè wilì providå rationalå foò fisherieó manageró 

tï betteò managå thå resourcå bù expendinç morå efforô tï preservå 

anä enhancå musseì bedó iæ theù arå showî tï bå selecteä oveò 

predominanô substrateó bù sporô fishes®  Improveä sporô fisherieó 

managemenô wilì bå reflecteä iî thå qualitù anä abundancå oæ thå 

resourcå anä wilì ultimatelù benefiô Illinois§ anglers.Š3.  Approach

     Personneì oæ thå Illinoió Naturaì Historù Surveù (INHS© 

Riveò Researcè Laboratorù (RRL© wilì conducô thå study®  

Laboratorù experimentó wilì evaluatå thå importancå oæ musseì 

bedó tï thå sporô fisherù bù monitorinç fisè locatioî iî 

experimentaì tankó tï determinå anä evaluatå fisè preferencå foò 

musseì beä substrates.


4.  Location

     Laboratorù studieó wilì bå conducteä iî thå basemenô oæ thå 

Illinoió Departmenô oæ Conservatioî (DOC© Fisherieó Fielä 

Headquarters¬ Havana¬ Illinois®  Fisè anä musseló useä iî thió 

researcè wilì bå collecteä froí thå Illinoió anä Mississippé 

rivers®  Datá wilì bå analyzeä aô thå INHÓ Riveò Researcè 

Laboratory¬ Havana¬ anä thå Universitù oæ Illinois¬ Champaigî 

Urbana¬ Illinois.


Studù 101®  Valuå oæ Musseì Bedó tï thå Sporô Fishery

Studù Objective

     Tï evaluatå thå significancå oæ musseì bedó tï thå sporô 

fishery.


Justification

     Propeò managemenô oæ thå sporô fisherù requireó 

identification¬ preservation¬ anä enhancemenô oæ thoså habitató 

mosô attractivå tï sporô fisè foò spawning¬ feeding¬ anä foò 

nurserù areas®  Althougè iô ió suspecteä thaô musseì bedó arå 

selecteä oveò predominanô substrateó bù sporô fish¬ thå relativå 

significancå oæ thå bedó tï thå sporô fisherù haó noô beeî 

evaluated®  Iæ sporô fisheó selecô musseì bedó oveò predominanô 
Šsubstrates¬ increaseä efforô tï preservå anä enhancå musseì bedó 

shoulä contributå tï thå protectioî anä enhancemenô oæ sporô 

fisheries.

     Iô ió importanô thaô thå relationshipó betweeî thå sporô 

fisherù anä musseì bedó bå evaluateä now¬ becauså present-daù 

pressureó maù bå reducinç bivalvå populationó significantly®  

Exampleó oæ sucè pressureó includå thå aó yeô unexplaineä musseì 

die-offó (Neveó iî preparation)¬ effectó causeä bù commerciaì 

navigatioî (Miller¬ pers® comm® 1986© anä fleetinç (Sparkó anä 

Blodgetô 1985)¬ anä increasinç harvesô pressurå (Fritú 

unpublisheä data)®  Iæ iî facô musseì bedó arå importanô tï 

preservinç anä enhancinç thå sporô fishery¬ manageró musô takå 

stepó no÷ tï protecô musseì beds.


Status

     Musseì bedó maù contributå tï thå sporô fisherù bù providinç 

attractivå substratå foò feeding¬ spawning¬ oò nurserù habitat®  

Sephtoî eô al® (1980© founä increaseä averagå numericaì abundancå 

oæ macroinvertebrateó iî sampleó containinç bivalveó compareä 

witè thoså withouô bivalves¬ possiblù becauså thå faeceó anä 

pseudofaeceó oæ thå musseló providå á valuablå fooä sourcå foò 

nonbivalvå filterinç detritivoreó (Izveková anä Lvova-Katchanová 

1972)®  Theså nonbivalvå macroinvertebrateó arå iî turî utilizeä 

bù variouó specieó anä agå classeó oæ fishes®  Musseì bedó 

providå á firí placå oæ attachmenô foò aquatiã insectó (Andersoî 

anä Vinikouò 1984© iî aî environmenô otherwiså dominateä bù 

shiftinç alluvium®  Musseló maù perforí thå samå functioî foò 

eggó oæ somå sporô fisheó sucè aó whitå basó (Moronå chrysops)¬ 

walleyå (Stizostedioî vitreum)¬ anä saugeò (Stizostedioî 
Š
canadense)®  Thå livinç musseì maù bå á morå valuablå substratå 

foò thå insectó anä fisè eggó thaî thå deaä shelló becauså iô 

continuouslù adjustó itó positioî tï keeğ itó pseudosiphonó anä 

á portioî oæ itó shelì abovå thå mud-wateò interface¬ eveî durinç 

periodó oæ deposition¬ thuó keepinç itó "hitchhikers¢ froí beinç 

smothered®  Increaseä fooä quantitù anä qualitù maù makå bedó 

attractivå fisè nurserieó anä providå structurå thaô juvenilå 

fisè neeä tï escapå froí predators®  Greateò densitieó oæ 

juvenilå fisè anä foragå fisè contributå tï á greateò fooä supplù 

foò piscivorouó sporô fish.

     Anotheò linå oæ evidencå suggestinç fisè frequenô musseì 

bedó ió thå lifå cyclå oæ freshwateò mussels®  Musseló havå á 

nonmotilå stage¬ calleä á glochidium¬ whicè musô attacè tï anä 

parasitizå á fisè iî ordeò tï transforí intï á free-livinç 

mussel®  Thå evolutioî oæ thió dependenô lifå cyclå suggestó á 

spatiaì associatioî betweeî thå fisè hostó anä thå mussels¬ aô 

leasô durinç thå timå wheî thå glochidiá arå beinç releaseä froí 

thå femalå mussels.


Procedures

Job 101.1  

Objectiveº  Tï revie÷ literaturå tï evaluatå effectó thaô musseì 

     bedó havå oî thå ecosysteí whicè mighô bå beneficiaì tï thå 

     sporô fishery.


Job 101.2  

Objectiveº  Tï seô uğ holdinç tanks¬ construcô tesô tanks¬ 

     interfacå computeró anä cameras¬ anä writå necessarù 

     softwarå tï tesô fisè foò substratå preferenceó iî Jobó 
Š     101.µ anä 101.6®  Dimensionó anä materialó foò thå tankó arå 

     described starting on page 6.


Job 101.3

Objectiveº  Tï collecô musseló froí thå Illinoió and/oò 

     Mississippé rivers anä establisè anä maintaiî musseì 

     populationó iî thå experimentaì tanks®  Seå pageó ¶ ff® foò 

     details on species and stocking densities.


Job 101.4

Objectiveº  Tï collecô anä maintaiî fisè tï bå testeä foò 

     substratå preferences®  Seå pageó ¶ ff® foò detailó oî 

     specieó anä holdinç densities® 


Joâ 101.5

Objectiveº  Tï determinå whetheò representativå sporô anä foragå 

     fisè residinç iî thå Illinoió oò Mississippé riveró clearlù 

     prefeò musseì bedó tï otheò substratå types.


Job 101.6

Objectiveº  Tï investigatå somå oæ thå factoró (feeding¬ 

     spawning¬ nursery© whicè maù bå responsiblå foò anù 

     demonstrateä preferenceó sporô fisheó displaù foò musseì beä 

     substrate.


Job 101.7

Objectiveº  (1© Tï preparå á reporô evaluatinç thå experimentaì 

     resultó anä thå valuå oæ musseì bedó tï thå sporô fishery®  

     (2©  Iæ thå resultó arå positivå (i.e.¬ sporô fisè dï prefeò 

     musseì bedó tï otheò substrates© thå reporô wilì recommenä 

     follow-uğ demonstrationó (includinç meso-scalå fielä 
Š     experiments© anä managemenô approacheó foò maintaininç anä 

     enhancinç thå benefitó oæ musseì bedó foò sporô fishes.


     Musseló anä fisè wilì bå helä separatelù iî existinç 

fiberglasó tanks¬ approximatelù 0.¶ í widå ø 0.¶ í talì ø 1.¸ 

long®  Fisè holdinç tankó wilì havå nï substratå anä wilì receivå 

á continuouó flo÷ oæ unchlorinateä welì wateò whicè haó beeî 

aerateä iî á separatå reservoiò untiì thå D.O® ió aô saturatioî 

anä thå temperaturå correspondó tï thå desireä acclimatioî 

temperature®  Musseló wilì bå placeä iî substratå takeî froí thå 

beä iî whicè theù werå collected¬ aô densitieó noô exceedinç 20° 

m-2” (thå maximuí densitù oæ livå musseló wå havå observeä iî thå 

Mississippé River)®  Thå musseì holdinç tankó wilì bå maintaineä 

aô thå acclimatioî temperaturå anä wilì receivå á continuouó flo÷ 

oæ aerateä Illinoió Riveò water¬ whicè containó thå finå 

particulatå matteò oî whicè thå musseló feed.

     Controlleä laboratorù experimentó wilì bå useä iî Jobó 101.µ 

anä 101.¶ tï detecô anä evaluatå anù preferencå sporô fisheó havå 

foò musseì beä substratå oveò ³ substrateó containinç nï musselsº  

(1© sand/silt¬ (2© gravel¬ anä (3© gravel/cobble¬ includinç rockó 

that approximate the size and shape of mussels.  Threå setó oæ 

tesô apparatus¬ eacè consistinç oæ twï flow-througè chambers--

an experimentaì anä á controì (Figurå 1)¬ wilì bå constructeä oæ 

glasó oò plexiglaó anä siliconå rubber®  Á uniforí flo÷ oæ wateò 

througè thå chamberó wilì bå maintaineä bù aî upstreaí bafflå 

madå oæ plexiglas®  Alì constructioî materialó wilì bå nontoxicº  

stainlesó steel¬ glass¬ plexiglas¬ siliconå rubber¬ nyloî anä 

tefloî impelleró iî thå wateò pumps¬ anä polyethylenå oò Tygoî 

tubing®  Thå chamberó anä cameraó wilì bå iî á specially-
Šconstructeä rooí tï minimizå noiså anä disturbance®  Timer-

controlleä Vitalitå fluorescenô bulbó wilì providå á controlleä 

photoperioä whicè approximateó thå spectruí oæ naturaì sunlight®  

Durinç thå "dark¢ parô oæ thå photoperiod¬ á neaò infrareä lighô 

source¬ whicè thå fisè cannoô see¬ wilì providå sufficienô 

illumination for the cameras to operate.

     Musseló collecteä froí thå Illinoió and/oò Mississippé 

riveró anä acclimateä iî thå holdinç tankó wilì bå useä tï 

establisè á musseì beä oî onå sidå oæ eacè experimentaì chamber®  

Targeô musseì specieó arå Amblemá plicata¬ Megalonaiaó gigantea,“ 

Anodontá grandis,“ Leptodeá fragilis,“ Potamiluó laevissima¬ P.“ 

alatus¬ Quadrulá quadrula¬ Q® pustulosa¬ Truncillá donaciformis¬ 

anä T® truncata®  Theså specieó arå abundanô iî thå Illinoió 

and/oò Mississippé riveró anä arå knowî tï uså variouó sporô fisè 

aó glochidiaì hostó (Tablå 1)®  Thå experimentaì bedó wilì bå 

mixeä populations¬ witè thå proportioî oæ individualó oæ eacè 

specieó approximatinç thå proportionó founä iî primå bedó iî thå 

Mississippé anä loweò Illinoió rivers®  Thå stockinç densitù wilì 

totaì 60-20° livå musseló m-2¬ thå rangå founä iî primå beds®  

      Musseló wilì bå retaineä oî onå sidå oæ thå experimentaì 

tankó bù á stainlesó steeì wirå fencå whicè wilì extenä µ cí 

abovå thå substratå anä ruî dowî thå middlå oæ eacè tank®  Tï 

maintaiî thå bivalveó anä theiò associateä florá anä fauna¬ 

unfiltereä wateò froí thå Illinoió Riveò wilì bå circulateä 

througè thå tankó wheî fisè arå noô beinç tested®  

     Variouó specieó anä agå classeó oæ sporô fisè wilì bå 

collecteä froí thå Illinoió and/oò Mississippé riveró anä 

maintaineä iî á holdinç tanë iî thå laboratory®  Targeô specieó 

wilì bå sporô anä foragå fisè knowî tï bå hostó foò musseì specieó Š
occurrinç abundantlù iî thå rivers®  Onå sucè specieó ió thå whitå 

crappie--á hosô foò severaì musseì specieó includinç thå threå 

ridge¬ washboarä (Megalonaiaó gigantea)¬ pimplebacë (Quadrulá 

pustulosa)¬ anä pinë papershelì (Potamiluó laevissima)(Fulleò 

1974)®  Collecteä fisè wilì bå acclimateä anä maintaineä iî 

holdinç tankó iî thå laboratorù untiì theù arå testeä foò 

substratå preference®  Prioò tï usinç á fisè iî aî experimentaì 

tank¬ iô wilì firsô bå testeä iî á controì tanë tï determinå itó 

normaì behavior--whetheò itó positioî iî thå tanë ió randoí oò iæ 

iô selectó á certaiî locatioî oò locationó iî thå tank®  Tï tesô 

fish¬ welì wateò wilì bå useä tï slowlù dilutå thå riveò wateò 

untiì lighô penetratioî ió higè enougè tï monitoò thå fish'ó 

position (Ø anä Ù coordinates) usinç á MICRONEYÅ BULLEÔ PLUÓ 

camerá interfaceä tï aî APPLÅ IIGÓ computer®  Thå coordinateó 

wilì enablå uó tï determinå whicè sidå oæ thå tanë thå fisè ió iî 

anä itó heighô oveò thå substrate®  Positioî wilì bå determineä 

everù twï secondó anä storeä aó needeä oî 3.5¢ disks®  

     Afteò thå normaì behavioò oæ á fisè ió determined¬ iô wilì 

bå transferreä tï aî experimentaì tanë anä positioî wilì agaiî bå 

monitored®  Fisè positioî datá froí thå experimentaì tanë wilì bå 

compareä witè thoså froí thå controì tanë tï determinå whetheò oò 

noô thå fisè selecteä thå musseì beä oveò thå otheò substrateó 

(Joâ 101.5)®  Thå fielä oæ visioî oæ thå camerá wilì bå divideä 

intï ´ quadrantsº á lefô anä righô side¬ anä á toğ anä bottoí 

quadranô oî eacè side®  Thå numbeò oæ movementó intï anä ouô oæ 

eacè quadranô peò houò anä thå amounô oæ timå thå fisè spendó iî 

eacè quadranô durinç thå daù anä aô nighô wilì bå determined®  

Eacè fisè wilì servå aó itó owî control¬ sï thaô iæ onå individuaì 
Šspendó mosô oæ thå daylighô houró iî thå toğ lefô  quadranô iî thå 

controì chamber¬ buô increaseó itó timå iî thå quadranô abovå thå 

musseì beä iî thå experimentaì chambeò (aô thå expenså oæ timå 

spenô iî thå toğ lefô quadrant)¬ thå responså wilì bå considereä á 

significanô preference¬ eveî iæ thió individuaì stilì spendó morå 

timå aô thå toğ lefô thaî anotheò individual®  Thió experimentaì 

desigî ió commonlù useä iî behavioraì research¬ wherå thå samå 

individualó arå observeä oò testeä beforå anä afteò thå 

experimentaì treatmenô (traininç oò administratioî oæ somå drug)®  

Resultó wilì alsï bå graphicallù displayed¬ aó densitù plots¬ 

wherå thå densitù oæ shadinç increaseó witè thå numbeò oæ timeó 

thå fisè waó detecteä iî eacè quadranô (oò smalleò area¬ dowî tï 

thå bodù sizå oæ thå fisè oò pixeì sizå oæ thå camera).

     Iæ fisè arå showî tï selecô musseì bedó oveò thå sand/silô 

substrate¬ additionaì testó tï investigatå thå factor(s© 

responsiblå foò thå preferencå wilì bå conducteä (Joâ 101.6)®  

Theså includå testinç preferenceó foò livå musseló versuó deaä 

shelló anä foò musseló supportinç normaì Aufwuchó anä periphytoî 

versuó thoså whoså shelló havå beeî scrubbeä clean®  Iî addition¬ 

thå influenceó oæ environmentaì conditions¬ sucè aó photoperioä 

anä temperature¬ oî fisè selectioî oæ musseì bedó wilì bå 

evaluated®  Musseló maù givå ofæ chemicaì fisè attractantó wheî 

theù arå readù tï releaså theiò glochidia¬ oò fisè maù seeë musseì 

bedó wheî theù arå readù tï spawn®  Thå proposeä researcè wilì 

determinå whetheò thå preferencå oæ aô leasô ² specieó oæ fisè 

(tentatively¬ saugeò anä whitå crappie© foò musseì bedó changeó 

betweeî sprinç anä summer®  Identificatioî oæ á chemicaì 

attractant¬ iæ anù exist¬ woulä havå tï bå thå subjecô oæ á 

follow-uğ proposal.Š
     Aô leasô onå multispecieó tesô wilì bå conducted¬ iî whicè á 

largå piscivorå ió maintaineä witè á schooì oæ foragå fisè iî aî 

experimentaì chamber¬ anä thå movementó anä locationó oæ thå fisè 

monitored®  Thå resultó shoulä leaä tï somå interestinç questionó 

anä answeró regardinç foraginç behavior¬ predatoò refuges¬ anä 

habitaô utilization¬ witè usefuì managemenô implications®  Foò 

example¬ foragå fisè maù utilizå musseì bedó foò á refugå froí 

predators¬ buô thå predatoró maù benefiô iæ thå totaì populatioî 

oæ foragå fisè ió increaseä becauså theù finä food¬ shelter¬ anä 

spawninç substratå withiî thå musseì beds®  
.rm66

     Figurå ² presentó thå proposeä schedulå foò completioî oæ 

jobó assuminç á ± Octobeò 198· projecô initiation.
.paŠ

                            References

Anderson¬ R® V® anä W® S® Vinikour® 1984® Uså oæ molluscó aó 
     pupatioî siteó bù Oecetió inconspicua“  (Trichopteraº 
     Leptoceridae)® Journaì oæ Freshwateò Ecology®  2:417-422.

Fritz¬ A.W®  1986®   198µ Illinoió musseì shelì harvest®  
     Unpublisheä summarù oæ Illinoió musseì shelì harvesô 196³ - 
     1985.  Available from the author on request.

Fuller¬ S.L.H®  1974®  Clamó anä musseló (Mollusca:Bivalvia)®  Iî “ 
     Pollutioî ecologù oæ freshwateò invertebrates®  C.W® Harô anä 
     S.L.H® Fulleò (eds.)®  Academiã Press¬ Ne÷ York®  215-273.

Illinoió Deparmenô oæ Conservation®  1986®  Actioî foò thå 
     eightieó anä beyond» á strategiã plaî foò Illinoió fisherieó 
     resources¬ FY8· - FY88®  Volumå 1.  22p.

Miller¬ A®  1986®  U.S® Armù Corpó oæ Engineers¬ Waterwayó 
     Experimenô Station.  Personaì Communication.

Neves¬ R®  Iî preparation®  Proceedingó oæ thå workshoğ "Die-offó 
     oæ freshwateò musseló iî thå Uniteä States"®  Co-sponsoreä 
     bù thå U.S® Fisè anä Wildlifå Servicå anä thå Uppeò 
     Mississippi River Conservation Committee. 

Sparkó anä Blodgetô  1985®  Effectó oæ fleetinç oî mussels®  
     Illinoió Naturaì Historù Surveù Aquatiã Biologù Technicaì 
     Report¬ 1985(9)®  Prepareä foò thå Illinoió Departmenô oæ 
     Conservatioî anä thå Nationaì Marinå Fisherieó Service®  94p.

Sephton¬ T.W.¬ C.G® Patterson¬ anä C.H® Fernando®  1980®  Spatiaì 
     interrelationshipó oæ bivalveó anä nonbivalvå benthoó iî á 
     smalì reservoiò iî Ne÷ Brunswick¬ Canada®  Canadiaî Journaì 
     oæ Zoologù.  58º 853-859.

Izvekova¬ E.J.¬ anä A.A® Lvova-Katchanova®  1972®  Sedimentatioî 
     oæ suspendeä matteò bù Dreissená polymorphá (Pallas© anä itó 
     subsequenô utilizatioî bù Chironomidaå larvae®  Pol® Arch® 
     Hydrobiol®  19º 203-210.