


        
        
        
                                  Scope of Work
        
        
        
           Response of fish communities to Habitat Rehabilitation and 
        
        
             Enhancement Projects at Peoria Lake and Lake Chautauqua
                                                                                                        
        
        
                       1 October 1991 - 30 September 1992
        
        
        
                            Prepared 14 January 1992
                             by K. Douglas Blodgett
        
        
        
        
             Staff from the Illinois Natural History Survey's Long Term 
        
        Resource Monitoring Program (LTRMP) Field Station in Havana, IL 
        
        will collect fish data to determine the response of fish 
        
        communities to Habitat Rehabilitation and Enhancement Projects 
        
        (HREPs) on Peoria Lake and Lake Chautauqua.  As appropriate, 
        
        sampling equipment and methodologies will be compatible with 
        
        LTRMP Fisheries Protocols as documented in the LTRMP Methods 
        
        Manual.  A report will be prepared and submitted to the Rock 
        
        Island District, U.S. Army Corps of Engineers; the Environmental 
        
        Management Technical Center (EMTC) of the USFWS; and the Illinois 
        
        Department of Conservation.  The report will summarize sampling 
        
        and results to date.  In cooperation with the Rock Island 
        
        District and the EMTC, an expanded experimental design will be 
        
        developed and modified as necessary based on results.
        
        
        
        HREPMONITORING#1:92SOW


