NOTES TO VICKY AND DOUG



1.  CALL JACQUE SANDERS AS SOON AS POSSIBLE TO RESERVE THE COPIER 
AND OBTAIN ASSISTANCE FOR RUSS AND CARROLL.

2.  I FORGOT TO TELL EVERYONE TODAY THAT TOM KLAUSEN FROM THE 
AQUATIC BIOLOGY SECTION CALLED TO SAY THAT THERE WILL BE AN 
AQUATIC BIOLOGY PICNIC AT DR. LARRY LARIMORE'S CABIN ON THE SALT 
FORK OF THE VERMILION RIVER STARTING AT 3 P.M. ON SUNDAY, 5 
AUGUST.  THERE WILL BE BAR-B-Q CHICKEN AND A KEG OF BEER, AND 
PEOPLE ARE BEING ASKED TO BRING SIDE DISHES OR SNACKS.  RUSS AND 
CARROLL MAY WANT TO STAY OVER TO ATTEND THE PICNIC.  IT WOULD 
PROBABLY BE BEST IF THEY DROVE ONE OF THEIR OWN CARS IF THEY DO, 
SO IT DOES NOT APPEAR THAT THEY ARE USING A STATE VEHICLE FOR 
PERSONAL PURPOSES ON SATURDAY AND SUNDAY.  THE PARTY IS INTENDED 
FOR ALL THE SUMMER PEOPLE, INCLUDING THE INTERNS FROM EASTERN WHO 
WILL BE GOING BACK TO SCHOOL SOON.  

3.  TYPE UP A LIST OF INSTRUCTIONS FOR CARROLL AND RUSS.  THE 
HIGHEST PRIORITY IS TO GET A COPY OF THE LTER DRAFT REPORT TO 
PAUL RISSER BEFORE HE LEAVES FOR THE ESA/AIBS MEETING IN 
COLORADO.  THE ENVELOPES FOR RISSER, GORDEN, AND THE OTHER PIS 
SHOULD ALREADY BE TYPED, AND THE ONE FOR RISSER SHOULD HAVE A 
NOTE SAYING PLEASE DELIVER TO DR. RISSER BEFORE HE LEAVES FOR THE 
ESA/AIBS MEETING IN COLORADO.  IF RISSER HAS ALREADY GONE, BOB 
GORDEN COULD TAKE HIS COPY.  IF BOTH PAUL AND BOB HAVE ALREADY 
GONE, CHECK WITH JANA WAITE OR ALICE ADAMS (RISSER'S SECRETRAY) 
TO FIND OUT WHO WILL BE GOING ON SATURDAY.  THERE ARE QUITE A FEW 
PEOPLE GOING TO THE MEETING.

4.  THE REST OF THE COPIES HAVE LOWER PRIORITY.  IT WOULD BE NICE 
TO GET GORDEN'S TO HIM BEFORE HE LEAVES FOR THE MEETING.  THE 
OTHERS CAN BE DROPPED IN THE CAMPUS MAIL.  RICK ANDERSON'S COPY 
SHOULD BE BROUGHT BACK TO HAVANA WHEN HE COMES OVER TUESDAY OR 
WEDNESDAY, 7-8 AUGUST.  IN ADDITION TO THE PIS AND EXECUTIVE 
COMMITTEE, MAKE SURE COPIES ARE DROPPED IN THE CAMPUS MAIL TO 
RICH CAHILL, RODGER ADAMS, AND WAYNE WENDLAND.  OTHER COPIES 
SHOULD BE GIVEN TO PHYLLIS FOR THE U.S. MAIL (TO SAVE OUR STAMPS) 
FOR JIM KING, ILL. STATE MUSEUM.

5.  LOWER PRIORITY JOBS TO BE DONE IN CHAMPAIGN ARE:  PUMPING OUT 
THE BERTRAND CRUISER, ADDING ANTI-FREEZE TO THE ENGINE, AND 
REMOVING THE SENDING UNIT FOR THE DEPTH SOUNDER AND BRINGING IT 
BACK TO HAVANA, AND OBTAINING DISTILLED WATER OR AT LEAST LEAVING 
THE JUGS TO BE FILLED (MAKE SURE JUGS ARE TAKEN TO C-U).  THEY 
SHOULD ALSO BRING BACK THE MAIL FROM AQUATIC AND WILDLIFE OFFICES 
AND TAKE THE COME-ALONGS AND MAIL FROM HAVANA WHEN THEY GO.  THEY 
SHOULD CALL BACK IF THEY HAVE ANY PROBLEMS OR QUESTIONS. 

6.  PLEASE PROOFREAD ANY SECTIONS OF THE REPORT, SUCH AS SOME OF 
THE PAGES WITH THE FIGURE LEGENDS AND TABLES, AND # THE PAGES OF 
THE REPORT IN DARK PENCIL OR INK.


7.  I WILL PROBABLY BE AT HOME MOST OF FRIDAY MORNING AND LEAVE 
BEFORE LUNCH TO DRIVE DOWN TO THE CURRENT RIVER IN MISSOURI.  I 
PLAN TO COME BACK SUNDAY NIGHT OR MONDAY MORNING.  JACK GRUBAUGH 
WILL COME OVER ON TUESDAY AND WEDNESDAY TO DISCUSS RESULTS OF THE 
INTENSIVE SAMPLING AND HIS PAPER FOR THE GREAT PLAINS LIMNOLOGY 
CONFERENCE.  I AM STAYING ITH JACK COLE THE FORMER REFUGE MANAGER 
OF LAKE CHAUTAUQUA AND I DON'T THINK HIS CABIN HAS A PHONE.  I'M 
NOT PLANNING TO TAKE A MARINE RADIO IN MY KAYAK, SO I GUESS I'M 
GOING TO BE OUT OF TOUCH FOR TWO DAYS!!! 


